### ISSUE TITLE
Shrinking test cases

### ISSUE THREAD

**Issue by g2p** [rust-fuzz/honggfuzz-rs#11]
Is there an API that would yield the cov code of a given vector?
I'd like to be able to shrink test cases using custom code (truncating to a length determined from contents, for example), and such an API would provide a convenient way to do it.
Alternatively, a way to provide a function that yields shrink candidates would also work.
Or any other convenient way to achieve the same goal of shrinking test cases.

**Comment by PaulGrandperrin** [comment]
I reckon shrinking is not yet implemented in upstream [honggfuzz](https://github.com/google/honggfuzz).
There is this opened issue: google/honggfuzz#195 
What do you think @robertswiecki ?

**Comment by robertswiecki** [comment]
Hi,

By _function/API_ do you mean like a cmdline switch which would make honggfuzz into a one-pass mode with dumping coverage data and status about crashes?

**Comment by g2p** [comment]
I don't know enough about honggfuzz's preferred mode of interfacing. But that single-pass mode would work.
As far as how things would look like from the honggfuzz-rs point of view, a function yielding shrink candidates from inside the fuzzer target would be great.

**Comment by PaulGrandperrin** [comment]
It seems to me that this functionality is really dependant on the upstream project.
If it gets implemented someday, I'll sure make it available in honggfuzz-rs but in the meantime, I'll close this issue...
Thanks @g2p for the report!
