### ISSUE TITLE
Build with profiling

### ISSUE THREAD

**Issue by disconnect3d** [rust-fuzz/honggfuzz-rs#28]
It would be nice to have a `build-grcov` command that would build honggfuzz-rs with profiling support, so the fuzzed binary can later be run with all fuzzing-generated inputs and crashes to get the coverage data, e.g. through [Mozilla's grcov](https://github.com/mozilla/grcov).

This, more or less requires the build to use the following flags:
```
CARGO_INCREMENTAL=0 RUSTFLAGS='-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads'
```

**Comment by PaulGrandperrin** [comment]
closed by #29
