### ISSUE TITLE
honggfuzz-rs does not currently support Windows 

### ISSUE THREAD

**Issue by herou** [rust-fuzz/honggfuzz-rs#34]
Hello,
I am trying to install honggfuzz-rs but I am facing this issue: 

 honggfuzz-rs does not currently support Windows but works well under WSL (Windows Subsystem for Linux)
![image](https://user-images.githubusercontent.com/13895430/79170563-02c04700-7df0-11ea-8354-7a45774b03f4.png)

**Comment by PaulGrandperrin** [comment]
Hello,
Honggfuzz - the upstream project, not this project which is just a rust wrapper on it - does not support Windows.

Nothing can be done here, and I think the honggfuzz upstream developers and most people using fuzzers don't care at all about this platform so I guess I'll probably never be supported...
Linux is really the only fully supported platform, macOS and *BSD are kind of second class too.

So, as said in the error message, I recommend you to use WSL (version 2 is best) to have support if you work on Windows.
