### ISSUE TITLE
Not working on MacOS

### ISSUE THREAD

**Issue by shamatar** [rust-fuzz/honggfuzz-rs#35]
Build script does not trigger making required artifacts for MacOS.

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libhfcommon/libhfcommon.a(ns.o) has no symbols
Undefined symbols for architecture x86_64:
  "_mach_exc_server", referenced from:
      _wait_for_exception in arch.o
ld: symbol(s) not found for architecture x86_64
```

You can see how it can be hacked around in [here](https://github.com/shamatar/honggfuzz-rs).

**Comment by PaulGrandperrin** [comment]
@shamatar I sent a patch upstream to fix the root cause error.
I'll push a new honggfuzz-rs release as soon as my PR is pulled.
