### ISSUE TITLE
upgrade from 0.5.52 to 0.5.53 breaks

### ISSUE THREAD

**Issue by drahnr** [rust-fuzz/honggfuzz-rs#48]
```
error: failed to run custom build command for `honggfuzz v0.5.53`

Caused by:
  process didn't exit successfully: `/media/supersonic1t/projects/parity/rsc-perf/fuzzit/hfuzz_target/release/build/honggfuzz-e79e9d36b487ef79/build-script-build` (exit code: 1)
  --- stderr
  honggfuzz dependency (0.5.53) and build command (0.5.52) versions do not match
```

happens since the update in `Cargo.toml`.

**Comment by drahnr** [comment]
The git version with the same content works though

**Comment by drahnr** [comment]
The error message from `build.rs` should just be better I guess:

```
eprintln!("honggfuzz dependency ({}) and build command ({}) versions do not match",
                  VERSION, honggfuzz_build_version);
```

is not clear in what should be done to resolve the issue.

**Comment by PaulGrandperrin** [comment]
I guess you just need to `cargo install honggfuzz` again, so that your local binary matches the library dependency.
I agree, the message could be better.
Just adding a something like
`please adjust your Cargo.toml to "honggfuzz = \"{0}\"" or run "cargo install honggfuzz --version \"{1}\""`
