### ISSUE TITLE
`memmap` is unmaintained (RUSTSEC-2020-0077)

### ISSUE THREAD

**Issue by tizoc** [rust-fuzz/honggfuzz-rs#62]
See: https://rustsec.org/advisories/RUSTSEC-2020-0077.html

An alternative is https://github.com/RazrFalcon/memmap2-rs

**Comment by atouchet** [comment]
This was addressed in #55.

**Comment by PaulGrandperrin** [comment]
as @atouchet said, I merged #55 a long time ago but it seems `mapr` is getting unmaintained too :)
So as @tizoc suggested, I'm moving to `memmap2-rs`!
